name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
    name: Build binaries
    strategy:
      matrix:
        architecture: [amd64, '386', arm64, arm]
        os: [linux, darwin, windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: go build -o maxiban-${{ matrix.os }}-${{ matrix.architecture }}
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: LICENSE README.md
          binary_name: maxiban
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.architecture }}
