name: Publish

on:
  push:
    branches: [main]

jobs:
  tag:
    name: Bump tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

  build:
    permissions:
      contents: write
    needs:
      - tag
    name: Build binaries
    strategy:
      matrix:
        architecture: [amd64, '386', arm64, arm]
        os: [linux, darwin, windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: go build -o maxiban-${{ matrix.os }}-${{ matrix.architecture }}
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: LICENSE README.md
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.architecture }}
